version: '3.7'

services:
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - "8080:80"
    networks:
      - proxy
      - internal
    volumes:
      - ./docker/files:/srv
      
networks:
  proxy:
    external:
      name: proxy
  internal:


